export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_ALL_SETS = "SET_ALL_SETS";
export const SET_SET = "SET_SET";
export const CLEAR_SET = "CLEAR_SET";

export const SET_ALL_FLASHCARDS = "SET_ALL_FLASHCARDS";
export const SET_PUBLIC_SETS = "SET_PUBLIC_SETS";
export const SET_FLASHCARD = "SET_FLASHCARD";
export const CLEAR_FLASHCARD = "CLEAR_FLASHCARD";
export const CLEAR_ALL_FLASHCARDS = "CLEAR_ALL_FLASHCARDS";
